################################# Default configuration ###################
# provide your domain here
baseURL = "https://jptechnical.com"
# theme
theme = "hugo-theme-dream"
disqusShortname = ""
# site title
title = "JP | Technical - 907-748-2200"
# disable language
disableLanguages = [1]
# google analytics
# googleAnalytics = "UA-17780827-1" 
# unsafe html
[markup.goldmark.renderer]
unsafe = true



############################# Default Parameters ##########################
[params]
# logo is for all page
# logo = "/static/images/logo.png"
# logo white is for homepage logo, you can use colorful logo too...
# logo_white = "/static/images/logo.png"
# when logo is empty, it will shown your site title
googleAnalytics = "UA-17780827-1" # paste your analytics ID here. (UA-17780827-1)
disqusShortname = ""
customCSS = ["css/custom.css"]
favicon = "/images/favicon.ico"

# customize color
primary_color = "#003366"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://formspree.io/f/xqkwezry" # contact form works with : https://formspree.io
# Issue for this: https://github.com/themefisher/dot-hugo-documentation-theme/issues/162
# contact_form_action = "https://formspree.io/f/jp@jptechnical.com method=\"POST\"" # contact form works with : https://formspree.io


############################## social links ##############################

# [[params.social]]
# # icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
# icon = "instagram" # simpleicons.org
# name = "Instagram"
# link = "https://www.instagram.com/jptech_ak/"

# [[params.social]]
# # icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# icon = "twitter" # simpleicons.org
# name = "Twitter"
# link = "https://twitter.com/jptechnical"
  
# [[params.social]]
# # icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
# icon = "gitlab" # simpleicons.org
# name = "Gitlab"
# link = "https://gitlab.com/jptechnical"
  
# [[params.social]]
# # icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# icon = "linkedin" # simpleicons.org
# name = "Linkedin"
# link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright ©JP Technical, 2025" 
# banner
[Languages.en.params.banner]
title = "Is Your Business At Risk?</br> It Doesn't Have To Be!"
subtitle = "At JP Technical, we provide local Anchorage businesses with managed services, and an emphasis on Cybersecurity and Regulatory Compliance. We are fully HIPAA compliant, and we have applied the modern standards for cybersecurity, in our OWN business. More importantly, we have the tools and partners to help *YOU* to do so as well. <br><br>Let us help you **_SECURE YOUR BUSINESS_**, before it's too late. If you run a small business in Anchorage, Alaska, call us today for a free Security Risk Assessment, 907-748-2200."
bg_image = "/static/images/banner.gif"
placeholder = "Have a question? Search this site."

# call to action
[Languages.en.params.cta]
enable = true
title = "Do you need computer support for your business?"
content = "We have helped dozens of companies in Alaska to build a secure and resilient network. When work-from-home started, the only thing we had to do for our clients was help them source webcams and headsets, otherwise they were already capable of weathering the storm."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "services"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "services"
  name = "Antivirus & Antimalware"
  url = "antivirus-security"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "services"
  name = "Backup & Data Protection"
  url = "backup"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "services"
  name = "Remote Support"
  url = "remote-support"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "services"
  name = "Risk Management"
  url = "risk-management"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "services"
  name = "Windows & App Updates"
  url = "updates"
  weight = 1

[[Languages.en.menu.main]]
name = "standards"
weight = 5
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "standards"
  name = "Managed Services Plans"
  url = "standards/msp"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "standards"
  name = "General Terms & Conditions"
  url = "standards/tac"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "standards"
  name = "Recommended Technology Platform"
  url = "standards/rtp"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "standards"
  name = "Cybersecurity Essentials"
  url = "standards/cybersecurity"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "standards"
  name = "Privacy Policy"
  url = "/privacy"
  weight = 1


[[Languages.en.menu.main]]
name = "billing portal"
url = "billing"
weight = 6

